bot-api-token: 7710245164:AAGjpB5a5pYfO52Ifx4V2n7EPnOqcSFdjYE
solana-endpoint: https://delicate-magical-general.solana-mainnet.quiknode.pro/711c12c2a095854cb1ac263996cae4882a2fc12f
me-api-key: 34ec477e-262d-565d-9de4-89ec5b5dafe0
private-key: 2pMALEveioPHLFxZtukzyCNa9CCtRBxtV1QWdwJCrYS8jrJgSXX9jwb4pq5UC39YmugVJxwYbwjf5ohA1DfH2TPe
